version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production-planning
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: A3cWCJy-NsU8se#
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A3cWCJy-NsU8se#
      POSTGRES_DB: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
