spring:
  datasource:
#    url: jdbc:postgresql://db.kbuixjcdvubifvunqmjl.supabase.co:5432/postgres?user=postgres&password=A3cWCJy-NsU8se#  ONLY IPV6
    #url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.xbqibmckhwmzqjzuhklc&password=A3cWCJy-NsU8se#
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: A3cWCJy-NsU8se#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  output:
    ansi:
      enabled: always

logging:
  level:
    com.huawei: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8081